title: LEONARDO DA VINCI
baseURL: https://confident-archimedes-336817.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 15
    - name: Archive
      identifier: post
      url: /post/
      weight: 20



params:
  description: The best renesance UX Designer
  author1: Adam Melničák
  author2: Natálie Káčová
  author3: Štěpán Šindelka

